### ISSUE TITLE
 Add "Animation" and "Animation Série" categories support

### ISSUE THREAD

**Issue by lanzorg** [mancuniancol/script.magnetic.t411-mc#1] opened 2016-12-13 11:08 UTC
Could you include "Animation" category results for Movies and "Animation Série" category results for TV Shows?

**Comment by mancuniancol** [comment] 2016-12-13 11:32
The provider allows to configure it using its settings. It is each person who add support.

Please, go to the movie section and modify the url address:
http://www.t411.li/torrents/search/?search=QUERY&order=seeders&type=desc

Then modify the Query 1:
{title] {year}&subcat=631

Add the Query 2:
{title] {year}&subcat=455

Now, you are searching movies and animation.

For the series you can do the same.  The code is &subcat=637.

Those codes are found in the url address when you go to the website of t411.

I will close this issue, because your request is just configuration of the provider.

**Closed by mancuniancol** 2016-12-13 11:32 UTC

**Comment by mancuniancol** [comment] 2016-12-13 11:46
You need to turn off the checking by title

**Comment by mancuniancol** [comment] 2016-12-13 12:55
I've done update to the code to separate the query from the extra to keep enable the title filter.

Please, download provider version 0.9.0 and recall the defaults.  That step is mandatory.  You have to enter your T411's credentials.

This version only works with magnetic version 

The instructions are almost the same but:

Please, go to the movie section and modify the url address:
http://www.t411.li/torrents/search/?search=QUERY&EXTRA&order=seeders&type=desc

Then Add Extra 1:
subcat=631

Add the Query 2:
{title] {year}

Add the Extra 2:
subcat=455

The project is still beta, then I apologize for the lack of documentation.

**Comment by lanzorg** [comment] 2016-12-13 13:21
Awesome! Thanks you!

**Comment by mancuniancol** [comment] 2016-12-13 14:55
You need to have Magnetic version 0.9.55.  Otherwise, I won't get any result

**Comment by mancuniancol** [comment] 2016-12-13 15:15
I had a typo in the query

Add the Query 2:
{title} {year}


or you can use just
Query 2:
{title}

**Comment by mancuniancol** [comment] 2016-12-13 15:18
About the defaults.  My idea is leaving the decision to the user.  Then, the defaults are minimal.

**Comment by lanzorg** [comment] 2016-12-13 15:43
I noticed the typo. ;)
I don't know why but no WEB-DL* results anymore, even with the 0.8.1 release.
For example I can't get these results:
http://www.t411.li/torrents/search/?name=supernatural&description=&file=&user=&cat=210&subcat=433&term[46][]=951&term[45][]=978&term[7][]=1174&term[7][]=1175&search=%40name+supernatural

I have the same problem with others t411 addons for Quasar too.
Is this just fiixed bug the culprit?
https://github.com/scakemyer/quasar/commit/b3148b2942c64591e4c283a486eeb60eeac4d6e8

**Comment by mancuniancol** [comment] 2016-12-13 16:05
I can confirm that using this url for tv shows:

http://www.t411.li/torrents/search/?search=QUERY&EXTRA&subcat=433&order=seeders&type=desc&term[7][]=1174&term[7][]=1175

using query1:
{title}

and extra1:
term[45][]={season+967}&term[46][]={episode+936}

it works well. It gives me the two values.

Any case, just for the sake of the testing. Recall the default values


Another configuration will be:
http://www.t411.li/torrents/search/?search=QUERY&EXTRA&subcat=433&order=seeders&type=desc

using query1:
{title}

and extra1:
term[45][]={season+967}&term[46][]={episode+936}&term[7][]=1174&term[7][]=1175

**Comment by mancuniancol** [comment] 2016-12-13 16:07
QUERY will be replaces by Query1, Query2, etc.  And EXTRA for Extra 1, Extra 2, etc.

**Comment by lanzorg** [comment] 2016-12-13 16:57
Thank you for the clarification!
